### PR TITLE
Adding JSON diff test cases

### PR DESCRIPTION
**Pull request by erikbosch**
This is an idea on how we could improve vss-tools to catch regressions that we might introduce. The idea is to allow us to add an arbitrary number of models as test cases. The initial PR contains three test cases, relies on generating JSON and comparing output with reference output, but the framework could be used for other tests as well. Most likely our JSON output shall be quite stable, so the reference output shall likely be quite stable over time.

I think a framework like this could be useful as tests  (and reference examples) for e.g. #155, where we could add a number of test cases to cover various corner cases of layers/overlay. I am by no way a script/test expert, the solution can likely be improved but this seems to work.

### CODE REVIEW

**Comment by erikbosch** [comment]
This is how result is presented in the build:
image

**Comment by erikbosch** [comment]
In discussion with Daniel regarding if a Python-based test framework would be better. Converting it to a draft for now.

**Comment by danielwilms** [comment]
@danielwilms push PR

**Comment by SebastianSchildt** [comment]
Please check @danielwilms

**Comment by erikbosch** [comment]
Meeting decision to merge

**Pull request merged**
