### PR TITLE
Introducing new contrib structure

### PR DESCRIPTION
**Pull request by danielwilms**
Current contrib exporters live without major tool-updates.
 Proposal to do the following:
    1. create exporters for them in `vssexporters/contrib`
    2. dont create shortcut, but call them in Makefile with vspec2x --format <format>

### CODE REVIEW

**Comment by SebastianSchildt** [comment]
Would we add them as "optional" targets in CI?

**Comment by danielwilms** [comment]
> Would we add them as "optional" targets in CI?

Yes, that would be the idea

**Comment by danielwilms** [comment]
question: how to handle dependencies of contrib?

**Comment by danielwilms** [comment]
> question: how to handle dependencies of contrib?

@SebastianSchildt, can be done see https://github.com/COVESA/vss-tools/pull/172/commits/cd777735224075b95a51b928ad21bbb4f4247fd5. At the end try except would have to be done for each exporter in order to be sure that all, which can be imported are so. But that shouldn't be a huge problem.

**Comment by SebastianSchildt** [comment]
Hi, I like this pattern, Reasonably easy without the need to write a full blown "plugin loader". As this draft (due to the 2ttl?) relies on the extended attribute parameter, I suggest we get that nailed down first

**Comment by erikbosch** [comment]
@danielwilms - please finish this one before you leave for good.

**Comment by adobekan** [comment]
@danielwilms will create new PR.

**Pull request closed without merging**
