### PR TITLE
Binary Exporter fixes

### PR DESCRIPTION
**Pull request by SebastianSchildt**
Add some commits on top of #150 to make sure non binary exporters can run, without compiling the .so file for the binary version

### CODE REVIEW

**Comment by SebastianSchildt** [comment]
I think this does not fix automated builds, but not sure, as they are not running. Can you trigger them @erikbosch  @gunnarx ?

**Comment by erikbosch** [comment]
It seems to complain on that it cannot rebase due to conflicts @SebastianSchildt . Could you try to rebase to see if that qicks of the builds

**Comment by SebastianSchildt** [comment]
argh, I used Ulfs branch, maybe that is already messed up. Let me see...

**Comment by SebastianSchildt** [comment]
Ah running now, @UlfBj  you might want to check if binary/go_parser/parserlib/go.mod  (https://github.com/boschglobal/vss-tools/blob/exporter-refactor/binary/go_parser/parserlib/go.mod) is correct or broken. There was some conflict, I just choosed the require with "COVESA" instead of "GENIVI" in it, but not sure it is correct. 

If not, just comment the correct snippet
```
require (
   github.com/COVESA/vss-tools/binary/go_parser/datamodel v0.0.0-20211207094201-7208d48f32b6
)
```

And I can change it again

**Comment by SebastianSchildt** [comment]
It builds 🥳

**Comment by danielwilms** [comment]
@UlfBj please check, if works for you

**Comment by UlfBj** [comment]
I tested
make binary
and it worked correctly.

**Comment by SebastianSchildt** [comment]
Can be merged @erikbosch

**Pull request merged**
