### PR TITLE
Using rich for logging format, added .envrc

### PR DESCRIPTION
**Pull request by sschleemilch**
# About

Using [rich](https://rich.readthedocs.io/en/stable/introduction.html) as logging formatter for readability.

Before:
image

After:
image

Also added an [direnv](https://github.com/direnv/direnv) config for python3. Added gitignore entry accordingly

### CODE REVIEW

**Comment by sschleemilch** [comment]
Fixing the tests was a bit ugly since they are checking for stdout which changed now with rich.
Rich does adapt the output to the width of the terminal. If there is no terminal (such as in CI) the default value is 80.
So manually setting `COLUMNS` to 200 for the tests.
Overall I think the tests could be improved a lot.

Thoughts about them:

- Using `os.system` should be avoided and be replaced with `subprocess.run`
- Calling a subprocess could be avoided completely by just importing the module and running its `main()`
- Using host tools like `grep` and `cat` strikes out Windows support by design and are really not necessary `subprocess.run` can capture output and then a string check is quite simple
- Writing tests that are checking against stdout is not reliable and should be replaced by patching and looking at the Python logging module to see what messages have been received. That of course implies that we are importing the modules and not calling a new interpreter
- Not using a context based tempdir for tests but always removing things by hand is quite cumberstone. `with tempfile.TemporaryDirectory() as tmp` could be used to do that automatically

**Comment by erikbosch** [comment]
MoM: Please review

**Comment by sschleemilch** [comment]
Any findings? If not, mergy merge? :octocat:

**Comment by erikbosch** [comment]
> Any findings? If not, mergy merge? :octocat:

Unless a PR is trivial we typically give people a week for reviewing, i.e. announcing at one VSS Tuesday meeting, and then taking a merge decision at the next, or the day before if there is nothing reported. For larger ones possibly even longer review time. 

In this case (as it is quite technical) i do not think discussing it again at next meeting makes sense, but I will wait until Monday to see if anyone has any objections.

**Comment by sschleemilch** [comment]
> > Any findings? If not, mergy merge? :octocat:
> 
> Unless a PR is trivial we typically give people a week for reviewing, i.e. announcing at one VSS Tuesday meeting, and then taking a merge decision at the next, or the day before if there is nothing reported. For larger ones possibly even longer review time.
> 
> In this case (as it is quite technical) i do not think discussing it again at next meeting makes sense, but I will wait until Monday to see if anyone has any objections.

Okay, I thought this ones pretty trivial but all good

**Review by erikbosch — APPROVED** [review]
Looks good to me

**Comment by erikbosch** [comment]
The weekend has passed and no-one has filed any additional comments. Looks good to me, merging so that you can rebase the other PR.

**Pull request merged**
