### PR TITLE
✨ New exporter: go

### PR DESCRIPTION
**Pull request by sschleemilch**
Added new generator: go

It does produce structs to work with the vss tree.

It only produces simple structs for now. In future, we can also generate get/set methods and use the `allowed` as well as `min/max` fields.

### CODE REVIEW

**Comment by erikbosch** [comment]
Could you possibly add a README in https://github.com/COVESA/vss-tools/tree/master/docs that gives a bit on background and how the tool can be used or is intended to be used. Like linking to https://go.dev/ as possible not every one is familiar with Go.

We use Go in https://github.com/COVESA/vissr and I am curious if what we have here could be a replacement to the "binary" format currently used by that tool. ideas @UlfBj ?

**Comment by sschleemilch** [comment]
> Could you possibly add a README in https://github.com/COVESA/vss-tools/tree/master/docs that gives a bit on background and how the tool can be used or is intended to be used. Like linking to https://go.dev/ as possible not every one is familiar with Go.
> 
> We use Go in https://github.com/COVESA/vissr and I am curious if what we have here could be a replacement to the "binary" format currently used by that tool. ideas @UlfBj ?

Done. Added README: https://github.com/sschleemilch/vss-tools/blob/feature/go-exporter/docs/go.md

**Comment by sschleemilch** [comment]
Lets not merge it yet. I would like to make some improvements.

**Comment by erikbosch** [comment]
MoM:

- Erik: Not planned for 5.0
- Ulf: Did a quick review, this one generates structs, slightly different scope compared to binary format, which is language agnostic, so not a replacement for binary 
- Erik: Good if @UlfBj checks that code follows "good Go practice"
- Ulf: I can do it
- Please review

**Comment by UlfBj** [comment]
It looks good to me.

**Comment by erikbosch** [comment]
MoM: Ok to merge

**Pull request merged**
