### PR TITLE
Tests Refactoring

### PR DESCRIPTION
**Pull request by sschleemilch**
# About

Refactored tests mainly to make them independent of os specific tools and also to reduce complexity of cleaning up generated files:

- Not relying on os commands such as `grep`, `cat`, ...
- Using pytest's `tmp_path` and writing outputs to it instead of
  manually cleaning up artifacts
- Using `subprocess` instead of `os.system`
- Added `pytest-cov` and coverage infos as well as a coverage check > 90% in CI:

```
---------- coverage: platform darwin, python 3.11.9-final-0 ----------
Name                                                 Stmts   Miss  Cover   Missing
----------------------------------------------------------------------------------
src/vss_tools/__init__.py                                0      0   100%
src/vss_tools/vspec2binary.py                           11      1    91%   29
src/vss_tools/vspec2csv.py                              11      1    91%   29
src/vss_tools/vspec2ddsidl.py                           11      1    91%   29
src/vss_tools/vspec2franca.py                           11      1    91%   29
src/vss_tools/vspec2graphql.py                          11      1    91%   29
src/vss_tools/vspec2id.py                               11      1    91%   28
src/vss_tools/vspec2json.py                             11      1    91%   29
src/vss_tools/vspec2jsonschema.py                       11      1    91%   29
src/vss_tools/vspec2protobuf.py                         11      1    91%   29
src/vss_tools/vspec2yaml.py                             11      1    91%   29
src/vss_tools/vspec/__init__.py                        457     42    91%   33-36, 39, 65, 70, 95-96, 135-138, 167-169, 192, 206, 235, 254, 314, 648-655, 694, 707-714, 742, 752, 861-863, 900, 928, 964-965
src/vss_tools/vspec/loggingconfig.py                     4      0   100%
src/vss_tools/vspec/model/__init__.py                    0      0   100%
src/vss_tools/vspec/model/constants.py                 201      6    97%   106, 204-205, 227-231
src/vss_tools/vspec/model/exceptions.py                  9      1    89%   22
src/vss_tools/vspec/model/vsstree.py                   263     10    96%   111, 289-292, 383, 416, 478, 485, 564, 606-607
src/vss_tools/vspec/utils/__init__.py                    7      5    29%   16-23
src/vss_tools/vspec/utils/idgen_utils.py                25      0   100%
src/vss_tools/vspec/utils/stringstyle.py                 9      3    67%   16-18
src/vss_tools/vspec/utils/vss2id_val.py                 65      5    92%   134, 143-148, 158-159
src/vss_tools/vspec/vspec2vss_config.py                 10      0   100%
src/vss_tools/vspec/vspec2x.py                         106      4    96%   29-31, 174-175
src/vss_tools/vspec/vss2x.py                            11      1    91%   38
src/vss_tools/vspec/vssexporters/__init__.py             0      0   100%
src/vss_tools/vspec/vssexporters/vss2binary.py          88      7    92%   52, 94, 105, 109, 133-136
src/vss_tools/vspec/vssexporters/vss2csv.py             45      0   100%
src/vss_tools/vspec/vssexporters/vss2ddsidl.py         149     12    92%   67, 147-148, 160-162, 167, 176, 186, 237-238, 242
src/vss_tools/vspec/vssexporters/vss2franca.py          45      0   100%
src/vss_tools/vspec/vssexporters/vss2graphql.py         51      4    92%   105-109
src/vss_tools/vspec/vssexporters/vss2id.py              76      2    97%   120, 185
src/vss_tools/vspec/vssexporters/vss2json.py            69      1    99%   63
src/vss_tools/vspec/vssexporters/vss2jsonschema.py      79     31    61%   68, 71, 74-98, 101, 106, 109, 134-135, 142-145
src/vss_tools/vspec/vssexporters/vss2protobuf.py       117     14    88%   143, 147, 149-165
src/vss_tools/vspec/vssexporters/vss2yaml.py            70      3    96%   68-70
----------------------------------------------------------------------------------
TOTAL                                                 2066    161    92%
```

### CODE REVIEW

**Comment by erikbosch** [comment]
MoM:

- Erik: Please rebase after #367 has been rebased
- Nick: Seems to follow good practice
- Please review

**Comment by erikbosch** [comment]
The other PR is merged now, so this one can be rebased

**Comment by sschleemilch** [comment]
> The other PR is merged now, so this one can be rebased

Done. PR is ready

**Review by erikbosch — APPROVED** [review]
Looks good to me, I ran the test locally as below without problems. Will merge early next week unless anyone has any objections

```
poetry install
cd binary
make
 cd ..
 poetry run pytest
```

**Pull request merged**
