### PR TITLE
Fixes for compiler warnings and c++ support

### PR DESCRIPTION
**Pull request by eric-hologic**
The fix in 9fb1fc35e3d073e36ce71ad00a3143cd59ed8f8e looks like something to upstream. The others commits are FYI

### CODE REVIEW

**Comment by erikbosch** [comment]
Thanks for the pull request. I will bring it up for initial discussion at the next VSS meeting on Tuesday.

The DCO check fails. COVESA requires all contributions to be signed off. Please read https://covesa.global/about-covesa/#contribute-code After reading it add a sign-off to your commit `git commit --amend -s` and do a force push.

@UlfBj - could you possible assist with reviewing.

**Comment by UlfBj** [comment]
I am ok with having all the commits merged if that is what the commiter wants.

**Comment by eric-hologic** [comment]
Great - thank you.  Added sign-off information to commits as requested.

**Comment by erikbosch** [comment]
MoM: Merge

**Pull request merged**
