### PR TITLE
Migrating Android Code 

### PR DESCRIPTION
**Pull request by erikbosch**
We have some dormant code in the branch [code_generation](https://github.com/COVESA/vss-tools/tree/code_generation) containing a VSS-to-Android initiative. This PR proposes to integrate the code into master so that it easily can be referenced. As the code is a bit obsolete and likely cannot run as is on the latest vss/vss-tools I suggest that it is moved into "obsolete".

If we accept this PR we can delete the old branch. That many CI-checks fails is because the old commits do not fulfill our current way of working.

If we do not accept this PR I suggest keeping the old branch but renaming it to something more understandable, like `feature_vspec2aaproperties`

### CODE REVIEW

**Comment by erikbosch** [comment]
MoM:

- Gunnar explained the background
- Please review, possible merge decision next week
- Gunnar: You can discuss if you want all commits, or squash them

**Comment by erikbosch** [comment]
MoM:

- Stefan: Do we not have an Android group that should be involved
- Paul: Yes
- AP : Richard Fernandes to bring up this PR in COVESA Android Group and ask for feedback

**Comment by erikbosch** [comment]
MoM:

- Meeting was cancelled yesterday
- Three chairs
- AP: Erik to contact them to possibly get input for decision on next week VSS meeting

**Comment by RichardF35** [comment]
> MoM:
> 
> * Meeting was cancelled yesterday
> * Three chairs; Melina Mascolo, Richard Fernandes, GAUTRON Gabriel
> * AP: Erik to contact them to possibly get input for decision on next week VSS meeting

RF> Confirmed with AOSP App working group members - no concerns with pull request.

**Comment by erikbosch** [comment]
MoM: Merge

**Pull request merged**
