### PR TITLE
Protobuf import of structs

### PR DESCRIPTION
**Pull request by kkoppolu1**
## Summary
Import structs to protobuf using the following rules:

For data types:
1. Each branch gets its own proto file
2. The qualified name of the type is used to set up the proto package
3. The files are organized in directories mirroring the package

For signals:
1. Existing export logic is retained
2. Import statements are added for custom data types

Protobuf exporter is also consolidated into `vspec2x.py`

### Testing
- Unit tests
- Compile generated protobuf files to C++ using the protobuf compiler
- Unit tests also test for successful protobuf compilation

### Added dependencies
- protobuf compiler 

"Signed-off-by: Krishna Koppolu krishnachaitanya.85@gmail.com"

https://github.com/COVESA/vss-tools/issues/242

### CODE REVIEW

**Comment by erikbosch** [comment]
Meeting notes:

- Adnan and Krishna to review/check if single or multiple file is most common.
- Please review until next meeting

**Comment by kkoppolu1** [comment]
> 

Following the language guide - https://protobuf.dev/programming-guides/proto3/#adding-more-message-types
related messages can be in a single `.proto` file.

Since, types under a branch can be considered related, I am changing the exporter to create a single proto file per branch with all the types in it.

**Comment by erikbosch** [comment]
There is a conflict after merging some other PRs, should likely be easy to fix

**Review by erikbosch — APPROVED** [review]

**Comment by erikbosch** [comment]
Meeting decision: merge

**Pull request merged**
