### PR TITLE
Run mypy and remove some warnings on skipped methods

### PR DESCRIPTION
**Pull request by erikbosch**
This change results in that mypy is run as part of CI.
Mypy reports as of today some errors. Some of them shall better be fixed, other suppressed.
Currently the build succeeds even if mypy reports errors.
We can later when all errors have been fixed/suppressed change it so the build fails if mypy complains

### CODE REVIEW

**Comment by adobekan** [comment]
Interesting report.
"Found 40 errors in 10 files (checked 31 source files)"

**Review by adobekan — APPROVED** [review]
Looks good.

**Comment by erikbosch** [comment]
Meeting decision: Merge

**Comment by erikbosch** [comment]
Integrated the change from #209 into this PR as a workaround for the signoff problem. That change is as I see it trivial from an IP perspective so should not be a problem to contribute in my name

**Pull request merged**
