### PR TITLE
Removed C dependency from binary exporter

### PR DESCRIPTION
**Pull request by SebastianSchildt**
This removes the C dependency from the binary, making it pure Python.

That would make it also usable when installing the Pypi packages without compiling any additional dll

@UlfBj can you check this works for you? Only changes are in vss2binary.py

### CODE REVIEW

**Comment by sschleemilch** [comment]
Looks pretty good to me, would be great to remove that dependency 👍

**Review by sschleemilch — APPROVED** [review]

**Comment by erikbosch** [comment]
@SebastianSchildt - now there are conflicts

**Comment by SebastianSchildt** [comment]
> @SebastianSchildt - now there are conflicts

Rebased. Added some additional make-up to pass our new ruff bouncer

**Review by erikbosch — APPROVED** [review]
Looks good to me

**Comment by erikbosch** [comment]
@UlfBj - could you check if output is compatible

**Comment by erikbosch** [comment]
MoM:

- Ulf has not been able to test successfully, discussed in Slack. Great if it could be checked if it works for Ted
- Discussed in VISS slack (first)
- Great if more persons can test
- Sebastian: We miss quickstart for poetry (how to start vss-tools)
- Daniel: WoW - install poetry which can install venv
- Great if a PR to add it to a README could be created

**Comment by erikbosch** [comment]
I did a test on my Debian AMD64 VM comparing the output generated by this PR and latest master and the files were identical.

@UlfBj - what type of errors did you experience. Was it in generating the binary file, or that the binary file seems to be faulty? If it is latter case how can one try to reproduce it?

**Comment by erikbosch** [comment]
To me it seems that the build problems that Ulf experience is unrelated to this PR itself as he experience them also for master branch. I tested with a virgin Debian VM and did not experience any build problems, and the output generated with/without this PR was identical.

**Comment by erikbosch** [comment]
MoM:

- Merge

**Pull request merged**
