### PR TITLE
Consent tagging support added

### PR DESCRIPTION
**Pull request by UlfBj**

### CODE REVIEW

**Review by erikbosch — APPROVED** [review]
Looks good to me, but I am no user of the binary exporter.

**Comment by UlfBj** [comment]
This is a modification of the Go and C parsers only, the binary exporter code is untouched. 
Thanks for the review approval. 
A merge follow-up would be even more appreciated :)

**Comment by erikbosch** [comment]
@adobekan - I suggest that you decide if this one can be merged on the VSS meeting tomorrow.
My view is - There are no known users of the binary feature except Ulf, so no reason to have it open longer unless someone else states that they want more time for review

**Comment by adobekan** [comment]
12/12 meeting
- Ulf: binary is untouched. 
Decision to merge.

**Pull request merged**
